### ISSUE TITLE
Some CSS selectors are not working

### ISSUE THREAD

**Issue by Debaniya-n** [obsproject/obs-browser#419]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

none

### Expected Behavior

wrote a stylesheet with some specific selectors such as `div:has(ul>li>img[class*="n"][src*="n"])` for [discord streamkit voice overlay. ](https://streamkit.discord.com/overlay)
it worked as expected on chrome with this result when talking:
![msedge_0JVr3ve4gw](https://github.com/obsproject/obs-browser/assets/30012320/594023aa-c4de-4b32-9035-cff14f96e5a4)
the code in question: 
```css

div:has(>ul>li>img[class*="Speaking"][src*="LEFT ID"]){
    animation-name: speak-now ;
    animation-duration: 1s ;
    animation-fill-mode:forwards ;
    -webkit-animation: speak-now 1s  alternate;
    animation: speak-now 1s  alternate;
  }
  
@keyframes
    speak-now {
    0% { transform: translateY(0);  }
    15% { transform: translateY(-10px);  }
    30% { transform: translateY(0);  }
}
```

### Current Behavior

the same code in OBS did not result in the same behavior as in chrome as shown below:
![obs64_Z7ezoGPVTh](https://github.com/obsproject/obs-browser/assets/30012320/5458d2a3-1c03-4ed2-9e8c-3e125e20bd1c)

### Steps to Reproduce

1. Add browser source of said overlay,
2. Paste the code in Expected Behavior form above replacing `LEFT ID` at line 1 with your own discord User ID in the custom css section.
3. Result will be different than having the css added to the overlay page on a Chrome Tab
